Cmake integration WIP

diff --git a/cmake/drivers/bsvc b/cmake/drivers/bsvc
--- a/cmake/drivers/bsvc
+++ b/cmake/drivers/bsvc
@@ -32,71 +32,90 @@ fi
 #
 # Parse options
 #
-INPUT_FILE=""
-OUTPUT_FILE=""
+OUTPUT=""
 INCLUDE_DIRECTORIES=("%/Libraries")
 
-while getopts "i:o:I:v" OPTION; do
-    case $OPTION in
-        i)
-            INPUT_FILE=$OPTARG
-            ;;
-        o)
-            OUTPUT_FILE=$OPTARG
-            ;;
-        I)
-            INCLUDE_DIRECTORIES+=("$OPTARG")
-            ;;
-        v)
-            VERBOSE=true
-            ;;
-        :)
-            echo "[bsvc] ERROR: Invalid Option: -$OPTARG requires an argument" 1>&2
-            exit 1
-            ;;
-        \?) # Invalid option
-            echo "[bsvc] ERROR: Invalid option: $OPTION"
-            exit 1
-            ;;
-    esac
-done
-shift $((OPTIND -1))
+POSITIONAL=()
+while [[ $# -gt 0 ]]; do
+    key="$1"
 
-#
-# Ensure required args are present
-#
-if [ -z "$INPUT_FILE" ]; then
-    echo "[bsvc] ERROR: -i option is required"
+    case $key in
+        -o|--output)
+            OUTPUT="$2"
+            shift # past argument
+            shift # past value
+            ;;
+        -I)
+            INCLUDE_DIRECTORIES+=("$2")
+            shift # past argument
+            shift # past value
+            ;;
+        --archive)
+            ARCHIVE=true
+            shift
+            ;;
+        -v|--verbose)
+            VERBOSE=true
+            shift # past argument
+            ;;
+        *)    # unknown option
+            POSITIONAL+=("$1") # save it in an array for later
+            shift # past argument
+            ;;
+  esac
+done
+
+if [ ${#POSITIONAL[@]} -eq 0 ]; then
+    echo "[bsvc] ERROR: No input files specified."
     exit 1
 fi
 
-if [ -z "$OUTPUT_FILE" ]; then
+if [ "$ARCHIVE" != "true" ] && [ ${#POSITIONAL[@]} -gt 1 ]; then
+    echo "[bsvc] ERROR: Extra arguments detected."
+    exit 1
+fi
+
+if [ -z "$OUTPUT" ]; then
     echo "[bsvc] ERROR: -o option is required"
     exit 1
 fi
 
-# Create the include directory spec by joining all directories specified
-# delimited by a colon ':'
-#
-INCLUDE_DIRECTORIES_SPEC=$(join_by : "${INCLUDE_DIRECTORIES[@]}")
+if [ "$ARCHIVE" != "true" ]; then
+    INPUT_FILE=${POSITIONAL[0]}
 
-# Determine the output directory based on the dirname of the output specified
-OUTPUT_DIR=$(dirname "$OUTPUT_FILE")
+    # Create the include directory spec by joining all directories specified
+    # delimited by a colon ':'
+    #
+    INCLUDE_DIRECTORIES_SPEC=$(join_by : "${INCLUDE_DIRECTORIES[@]}")
 
-log "[bsvc] Command Line: '$BSV_COMPILER -u -bdir $OUTPUT_DIR -p $INCLUDE_DIRECTORIES_SPEC $INPUT_FILE'"
+    # Determine the output directory based on the dirname of the output specified
+    OUTPUT_DIR=$(dirname "$OUTPUT")
+    SOURCE_DIR=$(dirname "$INPUT_FILE")
 
-# Run the compiler
-$BSV_COMPILER -u -bdir "$OUTPUT_DIR" -p "$INCLUDE_DIRECTORIES_SPEC" "$INPUT_FILE"
+    log "[bsvc] Command Line: '$BSV_COMPILER -u -bdir $OUTPUT_DIR -p $SOURCE_DIR:$INCLUDE_DIRECTORIES_SPEC $INPUT_FILE'"
 
-# bsc outputs foo.bo for inputs of foo.bsv which may not be what CMake expects.
-# If the output file is different than what CMake expects copy it.
-OUTPUT_FILENAME_EXPECTED=$(basename "$OUTPUT_FILE")
-OUTPUT_FILENAME_ACTUAL=$(basename "$INPUT_FILE" .bsv).bo
+    # Run the compiler
+    $BSV_COMPILER -u -bdir "$OUTPUT_DIR" -p "$SOURCE_DIR:$INCLUDE_DIRECTORIES_SPEC" "$INPUT_FILE"
 
-if [ "$OUTPUT_FILENAME_EXPECTED" != "$OUTPUT_NAME_ACTUAL" ]; then
-    OUTPUT_FILE_SOURCE="$OUTPUT_DIR/$OUTPUT_FILENAME_ACTUAL"
-    OUTPUT_FILE_DEST="$OUTPUT_DIR/$OUTPUT_FILENAME_EXPECTED"
+    # bsc outputs foo.bo for inputs of foo.bsv which may not be what CMake expects.
+    # If the output file is different than what CMake expects copy it.
+    OUTPUT_FILENAME_EXPECTED=$(basename "$OUTPUT")
+    OUTPUT_FILENAME_ACTUAL=$(basename "$INPUT_FILE" .bsv).bo
 
-    log "[bsvc] Copying $OUTPUT_FILE_SOURCE to $OUTPUT_FILE_DEST"
-    cp "$OUTPUT_FILE_SOURCE" "$OUTPUT_FILE_DEST"
+    if [ "$OUTPUT_FILENAME_EXPECTED" != "$OUTPUT_NAME_ACTUAL" ]; then
+        OUTPUT_FILE_SOURCE="$OUTPUT_DIR/$OUTPUT_FILENAME_ACTUAL"
+        OUTPUT_FILE_DEST="$OUTPUT_DIR/$OUTPUT_FILENAME_EXPECTED"
+
+        log "[bsvc] Copying $OUTPUT_FILE_SOURCE to $OUTPUT_FILE_DEST"
+        cp "$OUTPUT_FILE_SOURCE" "$OUTPUT_FILE_DEST"
+    fi
+else
+    # Archive Mode
+    mkdir -p "$OUTPUT"
+
+    for OBJECT_FILE in "${POSITIONAL[@]}"
+    do
+        TARGET_NAME=$(basename $OBJECT_FILE .bsv.bo)
+        cp "${OBJECT_FILE}" "${OUTPUT}/${TARGET_NAME}.bo"
+    done
 fi
